# Generated by Django 5.0.6 on 2024-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['-time_create'], name='main_app_po_time_cr_02ac04_idx'),
        ),
    ]
