# Generated by Django 5.0.6 on 2024-05-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_category_posts_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.category'),
        ),
    ]
