# Generated by Django 5.0.6 on 2024-05-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tagpost_alter_posts_cat_posts_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdditionalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to='main_app.category'),
        ),
        migrations.AddField(
            model_name='posts',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='main_app.articleadditionaldescription'),
        ),
    ]
